config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :users, only: [:index, :show]
  resources :invitations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user

  def self.reacted?(id1, id2)
    case1 = !Invitation.where(user_id: id1, friend_id: id2).empty?
    case2 = !Invitation.where(user_id: id2, friend_id: id1).empty?
    case1 || case2
  end
  
  def self.confirmed_record?(id1, id2)
    case1 = !Invitation.where(user_id: id1, friend_id: id2, confirmed: true).empty?
    case2 = !Invitation.where(user_id: id2, friend_id: id1, confirmed: true).empty?
    case1 || case2
  end
  
  def self.find_invitation(id1, id2)
    if Invitation.where(user_id: id1, friend_id: id2, confirmed: true).empty?
      Invitation.where(user_id: id2, friend_id: id1, confirmed: true)[0].id
    else
      Invitation.where(user_id: id1, friend_id: id2, confirmed: true)[0].id
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :Invitations
  has_many :pending_invitations, -> { where confirmed: false }, class_name: 'Invitation', foreign_key: 'friend_id'

  def friends 
    friend_send_invitation = Invitation.where(user_id: id, confirmed: true).pluck(:friend_id)
    friend_have_invitation = Invitation.where(friend_id: id, confirmed: true).pluck(:user_id)
    ids = friend_send_invitation + friend_have_invitation
    User.where(id: ids)
  end
  
  def friends_with?(user)
    Invitation.confirmed_record?(id, user.id)
  end
  
  def send_invitation
    invitations.create(friend_id: user.id)
  end

  def username
    return self.email.split('@')[0].capitalize
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController

  def create
    id1 = params[:ids][:id1]
    id2 = params[:ids][:id2]
    @invitation = Invitation.new(user_id: id1, friend_id: id2)
    @invitation.save
    redirect_to users_path
  end

  def update
    invitation = Invitation.find(params[:invitation_id])
    invitation.update(confirmed: true)
    redirect_to user_path(invitation.friend_id)
  end

  def destroy
    invitation = Invitation.find(params[:invitation_id])
    invitation.destroy
    redirect_to user_path(current_user.id)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">FriendApp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/users">Tous les utilisateurs</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_path(current_user.id) %>">Profil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= destroy_user_session_path %>" data-method='delete'>Se déconnecter</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">S'inscrire</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path %>">Se connecter</a>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendlySystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td>/</td>
        <% if signed_in? && !Invitation.reacted?(current_user.id, user.id) && current_user != user %>
          <td> <%= link_to 'Send Invitation',
            invitations_path(ids: {id1: current_user.id, id2: user.id}), method: :post
          %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/show.html.erb
<p> <%= @user.username %> || <%= @user.email %> </p>

<div class="container">
  <p>
    <strong>Nom :</strong>
    <%= @user.username %>
  </p>

  <p>Amis de <strong> <%= @user.username %> </strong> </p>

  <ol>
    <% @user.friends.each do |friend| %>
      <li>
        <%= friend.username %>
        <% if @user == current_user %>
          <%= link_to 'Retirer de la liste d\'amis', invitation_path(invitation_id: Invitation.find_invitation(@user.id, friend.id)), class:'btn btn-danger'  %>
        <% end %>
      </li>
    <% end %>
  </ol>

  <p> les demande d'amis pour <strong> <%= @user.username %> </strong> </p>

  <ol>
    <% @user.pending_invitations.each do |invitation| %>
      <li>
        <%= User.find(invitation.user_id).username %>
        <%= link_to "Accepter l'invitation", invitation_path(invitation_id: invitation.id), method: :patch, class:"btn btn-success" %>
        <%= link_to "Rejeter l'invitation", invitation_path(invitation_id: invitation.id), method: :delete, class:"btn btn-warning" %>
      </li>
    <% end %>
  </ol>
</div>